/* NOIACORE living system: cold editorial signal, liquid black space, evidence-led interaction, progressive disclosure. */
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Command, Github, Globe2, Linkedin, Mail, Menu, Terminal, X } from "lucide-react";
import { ProjectDossierGrid } from "@/components/ProjectDossierGrid";
import { ProtocolMap } from "@/components/ProtocolMap";

const heroImage = "/manus-storage/belentani-hero-liquid-protocol_15664367.png";
const signalImage = "/manus-storage/belentani-hero-signal-portrait_b2887c09.png";
const dataImage = "/manus-storage/belentani-user-portrait_41eb8863.png";
const monogramImage = "/manus-storage/belentani-pb-monogram_ba9c2ab8.png";

const projects = [
  { number: "01", category: "EXPEDIENTE / IA", title: "Meta-Builder Pipeline", description: "Cadena de modelos para comparar, evaluar y convertir respuestas de IA en decisiones trazables.", tags: ["Gemini", "DeepSeek", "Qwen"], tone: "neutral", image: dataImage, href: "https://github.com/belentani7", status: "ACTIVE", signal: "MULTI-MODEL ROUTING", detail: "Una capa de orquestación para comparar modelos, registrar decisiones y convertir exploración en ejecución auditable." },
  { number: "02", category: "EXPEDIENTE / RIESGO", title: "RELACIÓN.SCAN", description: "Sistema interactivo de análisis conductual basado en datos estructurados, anomalías y patrones de riesgo.", tags: ["Análisis", "Señales", "Privacidad"], tone: "neutral", image: signalImage, href: "https://github.com/belentani7", status: "FIELD", signal: "RISK INTELLIGENCE", detail: "Una lectura de relaciones, señales y anomalías diseñada para aumentar claridad sin convertir la intimidad en espectáculo." },
  { number: "03", category: "EXPEDIENTE / OPEN SOURCE", title: "OpenClaw", description: "Gateway de comunicación e integración de IA optimizado para arquitecturas ARM64 y entornos móviles.", tags: ["ARM64", "Termux", "CLI"], tone: "neutral", image: signalImage, href: "https://github.com/belentani7", status: "CORE", signal: "EDGE GATEWAY", detail: "Infraestructura ligera para mover capacidades de IA a entornos donde el contexto, la latencia y la autonomía importan." },
  { number: "04", category: "EXPEDIENTE / COMUNIDAD", title: "Manos Abiertas", description: "Iniciativa pública de alfabetización digital, IA y herramientas ofimáticas para ampliar autonomía tecnológica.", tags: ["Educación", "Web", "Acceso"], tone: "neutral", image: dataImage, href: "https://github.com/belentani7/manosabiertas", status: "PUBLIC", signal: "CAPABILITY ACCESS", detail: "Tecnología práctica para que más personas puedan entender, utilizar y gobernar herramientas digitales." },
];

const languages = [["es", "Español"], ["en", "English"], ["pt", "Português"], ["it", "Italiano"], ["fr", "Français"], ["ca", "Català"], ["fi", "Suomi"], ["zh", "中文"], ["hi", "हिन्दी"], ["ja", "日本語"], ["th", "ไทย"]];
const languageCopy = { es: { home: "Inicio", work: "Trabajo", about: "Perfil", contact: "Contacto", explore: "Explorar trabajo", channel: "Abrir canal" }, en: { home: "Home", work: "Work", about: "Profile", contact: "Contact", explore: "Explore work", channel: "Open channel" }, pt: { home: "Início", work: "Trabalho", about: "Perfil", contact: "Contacto", explore: "Explorar trabalho", channel: "Abrir canal" }, it: { home: "Inizio", work: "Lavoro", about: "Profilo", contact: "Contatto", explore: "Esplora il lavoro", channel: "Apri il canale" }, fr: { home: "Accueil", work: "Travail", about: "Profil", contact: "Contact", explore: "Explorer le travail", channel: "Ouvrir le canal" }, ca: { home: "Inici", work: "Treball", about: "Perfil", contact: "Contacte", explore: "Explorar el treball", channel: "Obrir canal" }, fi: { home: "Alku", work: "Työ", about: "Profiili", contact: "Yhteys", explore: "Tutki työtä", channel: "Avaa kanava" }, zh: { home: "首页", work: "工作", about: "简介", contact: "联系", explore: "查看工作", channel: "打开频道" }, hi: { home: "मुख्य", work: "कार्य", about: "प्रोफ़ाइल", contact: "संपर्क", explore: "कार्य देखें", channel: "चैनल खोलें" }, ja: { home: "ホーム", work: "仕事", about: "プロフィール", contact: "連絡先", explore: "仕事を見る", channel: "チャンネルを開く" }, th: { home: "หน้าแรก", work: "งาน", about: "โปรไฟล์", contact: "ติดต่อ", explore: "ดูผลงาน", channel: "เปิดช่องทาง" } } as const;
const protocolText = "BELENTANI PROTOCOL ACTIVATED";
const bootStages = ["SIGNAL CHECK", "CONTEXT VERIFIED", "PROTOCOL READY"];
const stack: Array<[string, number, string]> = [["Trust & Safety", 92, "CORE"], ["AI orchestration", 88, "CORE"], ["Automation / n8n", 86, "ACTIVE"], ["TypeScript / Python", 82, "ACTIVE"], ["Frontend systems", 79, "FIELD"], ["Security & audit", 84, "ACTIVE"]];
const timeline = [{ year: "2016—20", label: "OPERATIONS", detail: "Contexto, análisis y decisiones bajo presión." }, { year: "2020—23", label: "TRUST & SAFETY", detail: "Sistemas humanos para escalar criterio y proteger plataformas." }, { year: "2023—26", label: "NOIACORE LAB", detail: "IA, automatización y software con observabilidad." }];

function SectionLabel({ index, children }: { index: string; children: string }) { return <div className="section-label"><span>{index}</span><span>{children}</span></div>; }
function SignalBar({ label, state, level }: { label: string; state: string; level: number }) { return <div className="signal-bar"><div><span>{label}</span><b>{state}</b></div><div className="stack-bar" aria-hidden="true"><span style={{ width: `${level}%` }} /></div></div>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [terminalOpen, setTerminalOpen] = useState(false);
  const [command, setCommand] = useState("");
  const [output, setOutput] = useState(["belentani-cli v2.0.0", "Type 'help' to inspect the public system."]);
  const [loaded, setLoaded] = useState(false);
  const [now, setNow] = useState(new Date());
  const [language, setLanguage] = useState("es");
  const [bootText, setBootText] = useState("");
  const [bootStage, setBootStage] = useState("INITIALIZING");
  const [bootWelcome, setBootWelcome] = useState(false);
  const [filter, setFilter] = useState("ALL");
  const [selectedProject, setSelectedProject] = useState<(typeof projects)[number] | null>(null);
  const [activeProtocol, setActiveProtocol] = useState("SIGNAL / 00");
  const [commandPalette, setCommandPalette] = useState(false);
  const [systemPulse, setSystemPulse] = useState(82);
  const [machineState, setMachineState] = useState("OBSERVING");
  const copy = languageCopy[language as keyof typeof languageCopy] ?? languageCopy.es;

  useEffect(() => { document.documentElement.lang = language; }, [language]);

  useEffect(() => {
    const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reducedMotion) { setBootStage("READY"); setBootText(protocolText); setBootWelcome(true); setLoaded(true); }
    let reveal = 0;
    const stageTimers = reducedMotion ? [] : bootStages.map((stage, index) => window.setTimeout(() => setBootStage(stage), 900 + index * 1150));
    const decoder = reducedMotion ? undefined : window.setInterval(() => {
      reveal += 1;
      setBootText(protocolText.slice(0, reveal));
      if (reveal >= protocolText.length) { window.clearInterval(decoder); setBootStage("READY"); window.setTimeout(() => setBootWelcome(true), 1100); window.setTimeout(() => setLoaded(true), 3000); }
    }, 1150);
    const clock = window.setInterval(() => setNow(new Date()), 30000);
    const pulse = window.setInterval(() => setSystemPulse((value) => value > 96 ? 76 : value + 1), 4200);
    const keyboard = (event: KeyboardEvent) => { if (event.key === "Escape") { setSelectedProject(null); setCommandPalette(false); setMenuOpen(false); } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandPalette(true); } };
    window.addEventListener("keydown", keyboard);
    const observe = () => {
      const y = window.scrollY;
      const next = y < 420 ? "OBSERVING" : y < 1200 ? "CONTEXT READY" : y < 2300 ? "EVIDENCE OPEN" : y < 3400 ? "MEMORY UPDATED" : "CHANNEL AVAILABLE";
      setMachineState(next);
    };
    window.addEventListener("scroll", observe, { passive: true });
    observe();
    return () => { if (decoder) window.clearInterval(decoder); stageTimers.forEach((timer) => window.clearTimeout(timer)); window.clearInterval(clock); window.clearInterval(pulse); window.removeEventListener("keydown", keyboard); window.removeEventListener("scroll", observe); };
  }, []);

  const skipBoot = () => { setBootStage("READY"); setBootText(protocolText); setBootWelcome(true); setLoaded(true); };
  const localTime = useMemo(() => now.toLocaleTimeString("es-ES", { hour: "2-digit", minute: "2-digit" }), [now]);

  const runCommand = () => {
    const value = command.trim().toLowerCase();
    if (!value) return;
    const responses: Record<string, string> = { help: "commands: info · stack · contact · protocols · clear", info: "Pedro Belentani — Trust & Safety / AI Systems / Automation.", stack: "n8n · Ollama · Qwen · TypeScript · Python · Astro · GSAP", contact: "contacto@belentani.eu", protocols: "SIGNAL · CONTEXT · RISK · EXECUTION · ARCHIVE" };
    if (value === "clear") setOutput([]); else setOutput((current) => [...current, `guest@belentani:~$ ${value}`, responses[value] ?? `command not found: ${value}`]);
    setCommand("");
  };

  return <div className={`site-shell ${loaded ? "is-loaded boot-complete" : ""}`}>
    {!loaded && <div className="protocol-loader" role="status" aria-live="polite"><div className="loader-line" aria-hidden="true"><span/></div><div className="loader-code">SYS/00 · SIGNAL INITIALIZATION</div><div className="loader-stage">{bootStage}<span className="loader-cursor" aria-hidden="true" /></div><div className="loader-title">{bootText}</div><div className={`loader-welcome ${bootWelcome ? "is-visible" : ""}`}>BIENVENIDO A LA EXPERIENCIA</div><button className="loader-skip" onClick={skipBoot}>OMITIR SECUENCIA</button></div>}
    <div className="grain" aria-hidden="true" />
    <header className="site-header"><a className="brand-lockup" href="#top" aria-label="Belentani, inicio"><img src={monogramImage} alt="" className="brand-mark" /><span className="brand-wordmark">BELENTANI<span className="brand-dot">.</span>EU</span></a><nav className="desktop-nav" aria-label="Navegación principal">{[["00", copy.home, "top"], ["01", copy.work, "work"], ["02", copy.about, "about"], ["03", copy.contact, "contact"]].map(([n, label, href]) => <a key={n} href={`#${href}`}><span>{n}</span>{label}</a>)}</nav><div className="header-status"><span className="status-dot" /> AVAILABLE / BCN <span className="status-time">{localTime}</span></div><label className="language-picker"><Globe2 size={13}/><select aria-label="Seleccionar idioma" value={language} onChange={(event) => setLanguage(event.target.value)}>{languages.map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select></label><button className="menu-trigger" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></header>
    {menuOpen && <div className="mobile-menu"><div className="mobile-menu-inner">{[["00", copy.home, "top"], ["01", copy.work, "work"], ["02", copy.about, "about"], ["03", copy.contact, "contact"]].map(([n, label, href]) => <a key={n} href={`#${href}`} onClick={() => setMenuOpen(false)}><small>{n}</small>{label}<ArrowUpRight size={18}/></a>)}</div></div>}
    <main id="top">
      <section className="hero section-wrap"><div className="ambient-field" aria-hidden="true"><span className="ambient-ring ring-one"/><span className="ambient-ring ring-two"/><span className="ambient-beam"/><span className="ambient-particle particle-one"/><span className="ambient-particle particle-two"/><span className="ambient-particle particle-three"/></div><div className="hero-gridline" aria-hidden="true"/><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-pulse" /> SYS/00 — PROFESSIONAL PROFILE</div><h1>Calm systems<br /><em>under pressure.</em></h1><p className="hero-lede">Pedro Belentani es especialista en <strong>Trust & Safety</strong>, arquitecto de sistemas de IA y desarrollador de automatizaciones que mantienen la señal cuando el contexto se degrada.</p><div className="hero-actions"><a className="button button-primary" href="#work">{copy.explore} <ArrowUpRight size={16}/></a><a className="text-link" href="mailto:contacto@belentani.eu">{copy.channel} <span>↗</span></a></div><div className="hero-metadata"><span>Barcelona, ES</span><span>8+ años en operaciones críticas</span><span>Local-first / Open source</span></div></div><div className="hero-media"><div className="hero-image-frame"><img src={heroImage} alt="Retrato editorial de Pedro Belentani" /><div className="image-scanline"/><span className="image-index">PB / 2026</span><span className="image-coord">41°21' N<br />2°10' E</span></div><div className="hero-note note-a"><img src={monogramImage} alt="" className="seal-mark" />// integridad de señal<br /><strong>verificada</strong></div><div className="hero-note note-b">EXPEDIENTE<br /><strong>PB—01</strong></div></div><div className="scroll-cue"><span>SCROLL TO INSPECT</span><span className="scroll-line" /></div></section>
      <div className="motion-divider" aria-hidden="true"><span/><span/><span/></div><div className="ticker" aria-label="Áreas de especialización"><div className="ticker-track">TRUST & SAFETY <b>·</b> AI SYSTEMS <b>·</b> AUTOMATION <b>·</b> RISK INTELLIGENCE <b>·</b> CREATIVE TECHNOLOGY <b>·</b> TRUST & SAFETY <b>·</b> AI SYSTEMS <b>·</b> AUTOMATION <b>·</b> RISK INTELLIGENCE <b>·</b></div></div>
      <section id="work" className="section-wrap work-section"><div className="section-heading"><SectionLabel index="01" children="Expedientes seleccionados"/><p className="section-intro">Sistemas, experimentos e iniciativas públicas construidas en la intersección de operaciones, inteligencia y código.</p><a className="quiet-link" href="https://github.com/belentani7" target="_blank" rel="noreferrer">Abrir GitHub <ArrowUpRight size={15}/></a></div><ProjectDossierGrid projects={projects} filter={filter} onFilter={setFilter} onOpen={setSelectedProject} /></section>
      <section className="protocol-map section-wrap"><div className="section-heading"><SectionLabel index="01.5" children="Mapa de protocolos"/><p className="section-intro">La misma lógica recorre el sitio: detectar, contextualizar, decidir, ejecutar y archivar.</p></div><ProtocolMap active={activeProtocol} onChange={setActiveProtocol} /></section>
      <section id="about" className="section-wrap about-section"><div className="section-heading"><SectionLabel index="02" children="Perfil / método"/><p className="section-intro">Un perfil híbrido formado en operaciones críticas, análisis neutral y uso práctico de la IA como multiplicador de capacidad.</p></div><div className="about-layout"><div className="manifesto"><p className="manifesto-kicker">// THE CENTAUR PRINCIPLE</p><blockquote>“No trabajo contra la inteligencia artificial. Diseño el sistema que permite que una persona piense mejor, decida con más claridad y opere con menos fricción.”</blockquote><p>Más de ocho años en entornos corporativos globales de alta responsabilidad. Hoy conecto Trust & Safety, auditoría, automatización y desarrollo para construir sistemas que sean útiles, observables y difíciles de romper.</p><a href="mailto:contacto@belentani.eu" className="button button-outline">Conocer el perfil <ArrowUpRight size={16}/></a></div><div className="facts-panel"><div className="fact-row"><span>LOCATION</span><strong>Barcelona / EU</strong></div><div className="fact-row"><span>FOCUS</span><strong>Risk · AI · Systems</strong></div><div className="fact-row"><span>LANGUAGES</span><strong>ES · PT · CA · EN</strong></div><div className="fact-row"><span>STATUS</span><strong className="signal-text">AVAILABLE / SELECTIVE</strong></div><div className="fact-row"><span>PUBLIC SURFACE</span><strong>OPEN SOURCE / ACTIVE</strong></div><div className="fact-row"><span>LOCAL CLOCK</span><strong>BCN · {localTime}</strong></div></div></div><div className="timeline">{timeline.map((item) => <div className="timeline-node" key={item.year}><span>{item.year}</span><b>{item.label}</b><p>{item.detail}</p></div>)}</div></section>
      <section className="section-wrap stack-section"><div className="section-heading"><SectionLabel index="03" children="Lecturas operativas"/><p className="section-intro">Indicadores de experiencia aplicada: señales de trabajo real, no un ranking decorativo de habilidades.</p></div><div className="stack-layout"><div className="stack-list">{stack.map(([label, level, state]) => <div className="stack-item" key={label}><div><span>{label}</span><b>{state}</b></div><div className="stack-bar" aria-hidden="true"><span style={{ width: `${level}%` }}/></div></div>)}</div><div className="stack-note"><img src={dataImage} alt=""/><div><span className="eyebrow">SYS/03 — ARQUITECTURA</span><p>Desde el despliegue local de LLM hasta la automatización de workflows, construyo la capa entre la intención humana y una ejecución fiable.</p></div></div></div><div className="pulse-grid"><SignalBar label="SIGNAL INTEGRITY" state={systemPulse > 90 ? "STABLE" : "OBSERVED"} level={systemPulse}/><SignalBar label="CONTEXT RETENTION" state="TRACEABLE" level={88}/><SignalBar label="RECOVERY CAPACITY" state="RECOVERABLE" level={94}/></div></section>
      <section className="living-system section-wrap"><div className="living-orb" aria-hidden="true"><span/><span/><span/></div><div><SectionLabel index="03.5" children="Sistema vivo"/><h2>La interfaz también<br/><em>observa.</em></h2><p>Mientras lees, el sistema mantiene una señal de pulso, estados de protocolo y rutas de inspección. No es decoración: es una forma de explicar cómo trabajo.</p></div><div className="living-states"><div><span>STATE</span><b>{machineState}</b></div><div><span>NODE</span><b>BCN-01</b></div><div><span>LATENCY</span><b>LOW / STABLE</b></div><div><span>MODE</span><b>LOCAL-FIRST</b></div><div><span>TRACE</span><b>VISIBLE / LIVE</b></div></div></section>
      <section id="contact" className="section-wrap contact-section"><div className="contact-grid"><div><SectionLabel index="04" children="Abrir canal"/><h2>¿Hay un sistema<br/><em>que necesita pulso?</em></h2><p className="contact-copy">Consultoría, sistemas de IA, operaciones de Trust & Safety y producto cuidadosamente acotado. Cuéntame qué está en riesgo, qué se ha bloqueado o qué debería funcionar mejor.</p><a className="contact-email" href="mailto:contacto@belentani.eu">contacto@belentani.eu <ArrowUpRight size={22}/></a></div><div className="contact-side"><div className="availability-card"><span className="status-dot"/><div><strong>Disponible actualmente</strong><small>Para consultoría y proyectos de construcción seleccionados</small></div></div><div className="social-links"><a href="https://github.com/belentani7" target="_blank" rel="noreferrer"><Github size={18}/> GitHub <ArrowUpRight size={15}/></a><a href="https://www.linkedin.com/in/pedro-b-09473598/" target="_blank" rel="noreferrer"><Linkedin size={18}/> LinkedIn <ArrowUpRight size={15}/></a><a href="mailto:contacto@belentani.eu"><Mail size={18}/> Email <ArrowUpRight size={15}/></a></div></div></div></section>
    </main>
    <footer className="site-footer section-wrap"><div className="footer-brand"><img src={monogramImage} alt="" className="brand-mark footer-seal"/><span>CONSTRUIDO CON INTENCIÓN</span></div><div className="footer-meta"><span>© 2026 Pedro Belentani</span><span>v2.0 / SIGNAL ONLINE</span><span>Barcelona, ES</span></div></footer>
    <div className="terminal-wrap"><button className="terminal-toggle" onClick={() => setTerminalOpen(!terminalOpen)}><Terminal size={15}/> {terminalOpen ? "Close CLI" : "Open CLI"}</button>{terminalOpen && <div className="terminal"><div className="terminal-top"><span>belentani-cli</span><span>ESC</span></div><div className="terminal-output">{output.map((line, index) => <div key={index}>{line}</div>)}</div><div className="terminal-input"><span>guest@belentani:~$</span><input value={command} onChange={(event) => setCommand(event.target.value)} onKeyDown={(event) => event.key === "Enter" && runCommand()} autoFocus aria-label="Comando de terminal"/></div></div>}</div>
    {selectedProject && <div className="dossier-overlay" role="dialog" aria-modal="true" aria-labelledby="dossier-title" onClick={() => setSelectedProject(null)}><div className="dossier-modal" onClick={(event) => event.stopPropagation()}><button className="dossier-close" onClick={() => setSelectedProject(null)} aria-label="Cerrar expediente"><X size={18}/></button><div className="dossier-visual"><img src={selectedProject.image} alt=""/><span>{selectedProject.number} / {selectedProject.status}</span></div><div className="dossier-body"><span className="eyebrow">{selectedProject.category}</span><h2 id="dossier-title">{selectedProject.title}</h2><p>{selectedProject.detail}</p><div className="tag-row">{selectedProject.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><a className="button button-primary" href={selectedProject.href} target="_blank" rel="noreferrer">Ver señal pública <ArrowUpRight size={16}/></a></div></div></div>}
    {commandPalette && <div className="command-overlay" role="dialog" aria-modal="true" onClick={() => setCommandPalette(false)}><div className="command-palette" onClick={(event) => event.stopPropagation()}><div><Command size={16}/><input autoFocus placeholder="Inspeccionar el sistema…" onKeyDown={(event) => { if (event.key === "Enter") { setCommandPalette(false); document.getElementById("work")?.scrollIntoView({ behavior: "smooth" }); } }} /></div><span>⌘ K · ENTER TO INSPECT</span></div></div>}
  </div>;
}
